import os
import requests
import uuid
import msgpack
import time
import sys
import select
import queue
from keyboard import press_and_release
from dotenv import load_dotenv
from threading import Timer, Lock, Thread
from optparse import OptionParser
from cmd import Cmd

import config

################################################################################
# Local imports
################################################################################

from .exceptions import MsfRpcError
from .methods import MsfRpcMethod

################################################################################
# Envionment imports (API Keys etc)
################################################################################

load_dotenv()
MSF_SERVER = os.getenv('MSF_SERVER')
MSF_PORT = os.getenv('MSF_PORT')
MSF_USER = os.getenv('MSF_USER')
MSF_PASSWORD = os.getenv('MSF_PASSWORD')

################################################################################
# MSF Console
################################################################################

class MsfConsole(Cmd):
    prompt = 'msf>>>'

    def __init__(self):
        """
        Initialises an msf console object via RPC.

        Mandatory Arguments:
        - client : an msfrpc client object.
        """
        super(MsfConsole, self).__init__()
        self.client = None
        self.cid = None
        self.msf_lock = Lock()
        self.polling = False
        self.shell = False
        self.shell_verbose = False

    def connect(self, client):
        """
        Connect console to active msfrpc client
        """
        self.client = client
        # create a new msf console
        r = self.client.msf_callback(MsfRpcMethod.ConsoleCreate)
        if 'id' in r:
            self.cid = r['id']
        else:
            raise MsfRpcError("unable to create a new console")
        # discard metasploit startup output
        while self.check_busy():
            time.sleep(0.1)
        time.sleep(1) # wait for intro to print
        self.write_read()
        # check for unexpected outputs
        try:
            Thread(target=self.response_polling).start()
        except Exception as e:
            print("[!] Error: ", e)

    def response_polling(self):
        """
        Poll msfrpc for unexpected outputs,
        i.e commands not generated by callback function.
        """
        self.polling = True
        while self.polling:
            self.msf_lock.acquire()
            msf_reply = self.msfread()
            # if data, update prompt and display
            if 'data' in msf_reply.keys() and len(msf_reply['data']) > 0:
                self.prompt_update(msf_reply)
                # check if shell session
                if self.shell:
                    msf_data = msf_reply['data']
                    if self.shell_verbose:
                        self.display(msf_data)
                else:
                    print("[!] unexpected console data:")
                    self.display(str(msf_reply))
            self.msf_lock.release()
            time.sleep(0.5)

    def precmd(self, cmd):
        return Cmd.precmd(self, cmd)

    def write_read(self, cmd=None):
        """
        Write and read data to/from the msf server, with prompt update.
        Returns msf console response.
        """
        self.msf_lock.acquire()
        # send command
        self.msfwrite(cmd)
        # wait until console not busy
        self.wait_busy()
        # receive response
        msf_reply = self.msfread()
        self.msf_lock.release()
        return msf_reply

    def msfwrite(self, cmd=None):
        """
        Write data to msf server without waiting for a response.
        """
        # send command
        if cmd and not cmd.endswith('\n'):
            cmd += '\n'
        if cmd:
            opts = [self.cid, cmd]
            self.client.msf_callback(MsfRpcMethod.ConsoleWrite, opts)

    def msfread(self):
        """
        Read msf rpc console data.
        """
        opts = [self.cid]
        msf_reply = self.client.msf_callback(MsfRpcMethod.ConsoleRead, opts)
        # update msf prompt
        self.prompt_update(msf_reply)
        return msf_reply

    def prompt_update(self, msf_reply=None):
        """
        Update console prompt based on msfrpc reply.
        """
        if msf_reply == None:
            msf_reply = self.write_read('')
        if 'prompt' in msf_reply.keys() and \
            msf_reply['prompt'] != self.prompt:
                prompt = msf_reply['prompt'].replace('\x01', '')
                prompt = prompt.replace('\x02', '')
                self.prompt = prompt.replace("msf5 >", "msf>>>")

    def wait_busy(self):
        """
        Wait while the console is busy.
        """
        time.sleep(0.1)
        if self.check_busy():
            print('[*] msfconsole loading...')
        timer = 0
        while self.check_busy() and timer < 10:
            timer += 1
            time.sleep(1)
        if self.check_busy() and timer == 10:
            print('[!] msf console timeout: busy for >10s')

    def check_busy(self):
        """
        Checks if the console is busy. Return false if running shell.
        """
        if self.shell:

            return False
        msf_reply = self.client.msf_callback(MsfRpcMethod.ConsoleList)
        msf_consoles = msf_reply['consoles']
        for console in msf_consoles:
            if console['id'] == self.cid:
                busy_status = console['busy']
                return console['busy']
        raise Exception("[!] Busy check, console not found.")

    def display(self, cmd):
        """
        Write msf response string to display console
        """
        if self.shell_verbose:
            print('\n*********************************************************\n')
        cmd = cmd.replace('\x01', '')
        cmd = cmd.replace('\x02', '')
        cmd = cmd.replace('[*]', '[m]')
        cmd = cmd.rstrip()
        print(cmd)
        if self.shell_verbose:
            print('\n*********************************************************\n')

    def default(self, cmd):
        """
        Default console command, defined by cmd superclass.
        """
        self.callback(cmd)
        print('\n')

    def set_shell(self, shell=True):
        self.shell = shell

    def set_shell_verbose(self, verbose=True):
        self.shell_verbose = verbose

    def callback(self, cmd, verbose=True):
        """
        Forward cmd to msfrpc console then record and display response.
        Optional Arguments:
        - verbose: print to cmd by default, set to false to prevent print
        """
        if self.shell:
            self.msf_lock.acquire()
            msf_data = self.msfwrite(cmd)
            time.sleep(2)
            self.msf_lock.release()
            time.sleep(1)
        else:
            msf_data = self.write_read(cmd)['data']
            if verbose:
                self.display(msf_data)
            return msf_data

    def sessionkill(self):
        """
        Kill all active meterpreter or shell sessions.
        """
        self.client.msf_callback(MsfRpcMethod.ConsoleSessionKill, [self.cid])

    def sessiondetach(self):
        """
        Detach the current meterpreter or shell session.
        """
        self.client.msf_callback(MsfRpcMethod.ConsoleSessionDetach, [self.cid])

    def tabs(self, line):
        """
        Tab completion for console commands.
        Mandatory Arguments:
        - line : a partial command to be completed.
        """
        return self.client.msf_callback(MsfRpcMethod.ConsoleTabs, \
                                        [self.cid, line])['tabs']

    def destroy(self):
        """
        Destroy the console.
        """
        self.client.msf_callback(MsfRpcMethod.ConsoleDestroy, [self.cid])

    def stop_polling(self):
        self.polling = False

    def do_exit(self, cmd):
        """
        Exit the metasploit (msf) console
        """
        self.set_shell_verbose(verbose=False)
        return True

################################################################################
# Encoding
################################################################################

def convert(data):
    """
    Converts all bytestrings to utf8
    """
    if isinstance(data, bytes):  return data.decode('utf-8')
    if isinstance(data, list):   return list(map(convert, data))
    if isinstance(data, set):    return set(map(convert, data))
    if isinstance(data, dict):   return dict(map(convert, data.items()))
    if isinstance(data, tuple):  return map(convert, data)
    return data

def encode(data):
    return msgpack.packb(data)

def decode(data):
    return msgpack.unpackb(data)

################################################################################
# Option Parsing
################################################################################

def parseargs():
    p = OptionParser()
    p.add_option("-P", dest="password", \
                       help="Specify the password to access msfrpcd", \
                       metavar="opt")
    p.add_option("-S", dest="ssl", \
                       help="Disable SSL on the RPC socket", \
                       action="store_false", \
                       default=False)
    p.add_option("-U", dest="username", \
                       help="Specify the username to access msfrpcd", \
                       metavar="opt", \
                       default=MSF_USER)
    p.add_option("-a", dest="server", \
                       help="Connect to this IP address", \
                       metavar="host", \
                       default=MSF_SERVER)
    p.add_option("-p", dest="port", \
                       help="Connect to the specified port instead of 55552", \
                       metavar="opt", \
                       default=MSF_PORT)
    o, a = p.parse_args()
    if o.password is None:
        print('[-] Error: a password must be specified (-P)\n')
        p.print_help()
        exit(-1)
    return o

################################################################################
# Main
################################################################################

if __name__ == '__main__':
    # msf_console = MsfConsole(msf_client)
    # msf_console.cmdloop()
    pass

    # o = parseargs()
    # try:
    #     client = MsfClient(o.__dict__.pop('password'), **o.__dict__)
    #     console = MsfConsole(client)
    #     # m.interact('')
    # except MsfRpcError:
    #     print(str(client))
    #     exit(-1)
    # exit(0)
