# Provides the MsfConsole (Embedded Metasploit Console) class object 
#
# Author: Daniel Crouch
# Date created: March 2020


import os
import requests
import uuid
import msgpack
import time
import sys
import select
import queue
from keyboard import press_and_release
from dotenv import load_dotenv
from threading import Timer, Lock, Thread
from optparse import OptionParser
from cmd import Cmd

import config

################################################################################
# Local imports
################################################################################

from .exceptions import MsfRpcError
from .methods import MsfRpcMethod

################################################################################
# Envionment imports (API Keys etc)
################################################################################

load_dotenv()
MSF_SERVER = os.getenv('MSF_SERVER')
MSF_PORT = os.getenv('MSF_PORT')
MSF_USER = os.getenv('MSF_USER')
MSF_PASSWORD = os.getenv('MSF_PASSWORD')

################################################################################
# MSF Console
################################################################################

class MsfConsole(Cmd):
    prompt = 'msf>>>'

    def __init__(self):
        """
        Initialises an msf console object via RPC.

        Mandatory Arguments:
        - client : an msfrpc client object.
        """
        super(MsfConsole, self).__init__()
        self.client = None
        self.cid = None
        self.msf_lock = Lock()
        self.polling = False
        self.active_session = False
        self.verbose = False

    def connect(self, client):
        """
        Connect console to active msfrpc client
        """
        self.client = client
        # create a new msf console
        r = self.client.msf_callback(MsfRpcMethod.ConsoleCreate)
        time.sleep(1)
        if 'id' in r:
            self.cid = r['id']
        else:
            raise MsfRpcError("unable to create a new console")
        # discard metasploit startup output
        while self.check_busy():
            time.sleep(0.1)
        time.sleep(1) # wait for intro to print
        self.write_read()
        # check for unexpected outputs
        try:
            Thread(target=self.response_polling).start()
        except Exception as e:
            print("[!] Error: ", e)

    def response_polling(self):
        """
        Poll msfrpc for unexpected outputs,
        i.e commands not generated by callback function.
        """
        self.polling = True
        while self.polling:
            self.msf_lock.acquire()
            msf_reply = self.msfread()
            self.prompt_update(msf_reply)
            # if data, update prompt and display
            if 'data' in msf_reply.keys() and len(msf_reply['data']) > 0:
                # check if active session
                if self.active_session:
                    msf_data = msf_reply['data']
                    if self.verbose:
                        self.display(msf_data)
                        sys.stdout.write('\n' + self.prompt)
                        sys.stdout.flush()
                else:
                    print("[!] unexpected console data:")
                    self.display(str(msf_reply))
            self.msf_lock.release()
            time.sleep(1)

    def write_read(self, cmd=None, timeout=10, wait=0):
        """
        Write and read data to/from the msf server, with prompt update.
        Returns msf console response.
        """
        self.msf_lock.acquire()
        # send command
        self.msfwrite(cmd)
        # wait until console not busy
        self.wait_busy(timeout=timeout, wait=wait)
        # receive response
        msf_reply = self.msfread()
        self.msf_lock.release()
        return msf_reply

    def msfwrite(self, cmd=None):
        """
        Write data to msf server without waiting for a response.
        """
        # send command
        if cmd:
            cmd = cmd.strip() + '\n'
            opts = [self.cid, cmd]
            self.client.msf_callback(MsfRpcMethod.ConsoleWrite, opts)

    def msfread(self):
        """
        Read msf rpc console data.
        """
        opts = [self.cid]
        msf_reply = self.client.msf_callback(MsfRpcMethod.ConsoleRead, opts)
        # update msf prompt
        self.prompt_update(msf_reply)
        return msf_reply

    def prompt_update(self, msf_reply=None):
        """
        Update console prompt based on msfrpc reply.
        """
        if msf_reply == None:
            msf_reply = self.write_read('')
        if 'prompt' in msf_reply.keys() and \
            msf_reply['prompt'] != self.prompt:
                prompt = msf_reply['prompt'].replace('\x01', '')
                prompt = prompt.replace('\x02', '')
                self.prompt = prompt.replace("msf5 >", "msf>>>")

    def wait_busy(self, timeout=10, wait=0):
        """
        Wait while the console is busy.
        """
        time.sleep(0.1)
        # wait for response
        time.sleep(wait)
        # wait if busy
        if self.check_busy() and not self.active_session:
            config.LOADING = True
            timer = 0
            while self.check_busy() and timer < timeout:
                timer += 1
                time.sleep(1)
            if self.check_busy() and timer == timeout:
                print('\r[!] msf console timeout: busy for >10s')
            config.LOADING = False

    def check_busy(self):
        """
        Checks if the console is busy. Return false if running active shell.
        """
        msf_reply = self.client.msf_callback(MsfRpcMethod.ConsoleList)
        msf_consoles = msf_reply['consoles']
        for console in msf_consoles:
            if console['id'] == self.cid:
                busy_status = console['busy']
                return console['busy']
        raise Exception("[!] Busy check, console not found.")

    def display(self, string):
        """
        Write msf response string to display console
        """
        string = string.strip()
        if len(string) > 0:
            if self.verbose:
                print('\n\n    ' + str('=' *60) +'\n')
            for line in string.splitlines():
                line = line.replace('\x01', '')
                line = line.replace('\x02', '')
                line = line.replace('[*]', '[m]')
                line = line.rstrip()
                line = '    ' + line
                if line.startswith('    [') and not self.verbose:
                    line = line.strip()
                print('\r' + line[0:60])
                if len(line) > 60:
                    line_count = int(len(line) / 60)
                    for i in range(1,line_count +1):
                        sub_line = line[(i*60):((i+1)*60)]
                        print('    ' + sub_line)
            if self.verbose:
                print('\n\n    ' + str('=' *60) +'\n')

    def default(self, cmd):
        """
        Default console command, defined by cmd superclass.
        """
        if 'prompt' in cmd:
            pass
        else:
            self.callback(cmd)
            print('\n')

    def open_console(self):
        """
        Initialise and start console loop
        """
        self.prompt_update()
        self.set_verbose()
        self.set_active_session()
        self.cmdloop()

    def open_session(self, target_name, verbose=False):
        """
        Open an existing Metasploit session with remote host
        """
        target = config.TARGETS[target_name]
        self.set_active_session()
        cmd = "sessions -i " + target.session_id
        msf_reply = config.MSFCONSOLE.callback(cmd, verbose=verbose, wait=1)

    def background_session(self, target_name, verbose=False):
        """
        Background a currently open Metasploit session with remote host
        """
        target= config.TARGETS[target_name]
        cmd = "background"
        msf_reply = self.callback(cmd, verbose=verbose, wait=1)
        cmd = "back"
        msf_reply = self.callback(cmd, verbose=verbose, wait=1)
        self.set_active_session(active = False)
        print(msf_reply)

    def callback(self, cmd, verbose=True, timeout=10, wait=0):
        """
        Forward cmd to msfrpc console then record and display response.
        Optional Arguments:
        - verbose: print to cmd by default, set to false to prevent print
        """
        msf_data = self.write_read(cmd, timeout=timeout, wait=wait)['data']
        if verbose:
            if msf_data.startswith(cmd.strip()):
                # strip echoed commands
                msf_data = msf_data.replace(cmd.strip(), '', 1)
            self.display(msf_data)
        return msf_data

    def set_verbose(self, verbose=True):
        self.verbose = verbose

    def set_active_session(self, active=True):
        self.active_session = active

    def stop_polling(self):
        self.polling = False

    def do_cexit(self, cmd):
        """
        Exit the metasploit (msf) console
        """
        self.set_verbose(verbose=False)
        self.set_active_session(active=False)
        return True

################################################################################
# Encoding
################################################################################

def convert(data):
    """
    Converts all bytestrings to utf8
    """
    if isinstance(data, bytes):  return data.decode('utf-8')
    if isinstance(data, list):   return list(map(convert, data))
    if isinstance(data, set):    return set(map(convert, data))
    if isinstance(data, dict):   return dict(map(convert, data.items()))
    if isinstance(data, tuple):  return map(convert, data)
    return data

def encode(data):
    return msgpack.packb(data)

def decode(data):
    return msgpack.unpackb(data)

################################################################################
# Option Parsing
################################################################################

def parseargs():
    p = OptionParser()
    p.add_option("-P", dest="password", \
                       help="Specify the password to access msfrpcd", \
                       metavar="opt")
    p.add_option("-S", dest="ssl", \
                       help="Disable SSL on the RPC socket", \
                       action="store_false", \
                       default=False)
    p.add_option("-U", dest="username", \
                       help="Specify the username to access msfrpcd", \
                       metavar="opt", \
                       default=MSF_USER)
    p.add_option("-a", dest="server", \
                       help="Connect to this IP address", \
                       metavar="host", \
                       default=MSF_SERVER)
    p.add_option("-p", dest="port", \
                       help="Connect to the specified port instead of 55552", \
                       metavar="opt", \
                       default=MSF_PORT)
    o, a = p.parse_args()
    if o.password is None:
        print('[-] Error: a password must be specified (-P)\n')
        p.print_help()
        exit(-1)
    return o

################################################################################
# Main
################################################################################

if __name__ == '__main__':
    # msf_console = MsfConsole(msf_client)
    # msf_console.cmdloop()
    pass

    # o = parseargs()
    # try:
    #     client = MsfClient(o.__dict__.pop('password'), **o.__dict__)
    #     console = MsfConsole(client)
    #     # m.interact('')
    # except MsfRpcError:
    #     print(str(client))
    #     exit(-1)
    # exit(0)
