(define (domain attacksurface)
(:requirements :adl :typing)
(:types 	host service			 	- target
					host os port vuln 	- knowledge
					scan exploit 				- action)

(:predicates (is_host           												?x - host)
						 (has_session																?x - host)
						 (access_no_access													?x - host)
						 (access_user																?x - host)
						 (access_admin															?x - host)
						 (os_unknown     														?x - host)
						 (os_microsoft_windows_xp_service_pack_3		?x - host)
						 (os_microsoft_windows_xp_service_pack_2		?x - host)
						 (port_scanned		  												?x - host)
						 (full_scanned		  												?x - host)
			       (has_CVE_2007_6750 												?x - host)
			       (has_CVE_2008_4114 												?x - host)
			       (has_CVE_2008_4250 												?x - host)
			       (has_CVE_2010_0425 												?x - host)
			       (has_CVE_2011_3368 												?x - host)
			       (has_CVE_2011_4885 												?x - host)
			       (has_CVE_2012_1823 												?x - host)
			       (has_CVE_2014_0195 												?x - host)
			       (has_CVE_2014_0224 												?x - host)
			       (has_CVE_2014_3566 												?x - host)
			       (has_CVE_2017_0143 												?x - host)
			       (has_CVE_2017_0144 												?x - host)
			       (has_CVE_2017_0145 												?x - host)
			       (has_CVE_2017_0146 												?x - host)
			       (has_CVE_2017_0147 												?x - host)
			       (has_CVE_2017_0148 												?x - host)
			       (has_CVE_1999_0524 												?x - host)
			       (has_CVE_1999_0105 												?x - host)
			       (has_CVE_1999_0106 												?x - host)
			       (has_CVE_1999_0519 												?x - host)
			       (has_CVE_1999_0520 												?x - host)
			       (has_CVE_1999_0612 												?x - host)
			       (has_CVE_2002_1117 												?x - host)
			       (has_CVE_2003_1567 												?x - host)
						 (has_tcp_port_79														?x - host)
						 (has_tcp_port_80 													?x - host)
						 (has_tcp_port_139													?x - host)
						 (has_tcp_port_443 													?x - host)
						 (has_tcp_port_445 													?x - host)
						 (hist_exploit_cve_2008_4250 								?x - host)
						 (hist_exploit_msql_brute_force 						?x - host)
						 (hist_exploit_tokens												?x - host)
						 (hist_exploit_cve_2011_2005								?x - host)
						 (hist_exploit_hashdump											?x - host)
						 (has_progress1		  												?x - target)
						 (has_progress2     												?x - target))


 (:action port_scan
 	:parameters   (?x - host)
 	:precondition (not (port_scanned ?x))
 	:effect       (and (port_scanned ?x)
 								 		 (has_progress1 ?x))
 								)

(:action full_scan
	:parameters   (?x - host)
	:precondition (and (not (full_scanned ?x))
										 (port_scanned ?x))
	:effect       (and (full_scanned ?x)
								 		 (has_progress1 ?x))
								)

(:action exploit_cve_2008_4250
 	:parameters   		(?x - host)
 	:precondition 		(and (os_microsoft_windows_xp_service_pack_3 ?x)
 									  		 (has_CVE_2008_4250 ?x)
												 (access_no_access ?x)
												 (not (hist_exploit_cve_2008_4250 ?x)))
 	:effect      		  (and (not (access_no_access ?x))
												 (access_admin ?x)
 									  		 (has_progress1 ?x))
										)

(:action exploit_msql_brute_force
 	:parameters   		(?x - host)
 	:precondition 		(and (os_microsoft_windows_xp_service_pack_3 ?x)
												 (access_no_access ?x)
 									  		 (or (has_tcp_port_139 ?x)
												 		 (has_tcp_port_445 ?x))
												 (not (hist_exploit_msql_brute_force ?x)))
 	:effect      		  (and (not (access_no_access ?x))
												 (access_user ?x)
 									  		 (has_progress1 ?x))
										)

(:action exploit_tokens
 	:parameters   		(?x - host)
 	:precondition 		(and (access_user ?x)
 									  		 (or (has_tcp_port_139 ?x)
												 		 (has_tcp_port_445 ?x))
												 (not (hist_exploit_msql_brute_force ?x)))
 	:effect      		  (and (is_host ?x)
 									  		 (has_progress1 ?x))
										)

)
